<?xml version="1.0" encoding="UTF-8"?>
<bajadoc version="2.0" createdBy="niagara-baja-doclet-1.0.9" createdAt="03-May-2024" createdOn="883e7f7a9875">
<class module="baja" runtimeProfile="rt" qualifiedName="javax.baja.security.AuthenticationException" name="AuthenticationException" packageName="javax.baja.security" public="true" category="exception">
<description>
AuthenticationException is thrown when an operation fails&#xa; due to invalid authentication credentials.  If an instance&#xa; of AuthenticationException is created with an AuthenticationRealm,&#xa; then the application layer can catch this exception and prompt&#xa; the user to enter the credentials.
</description>
<tag name="@author">Brian Frank</tag>
<tag name="@creation">28 Jan 03</tag>
<tag name="@version">$Revision: 4$ $Date: 2/26/05 3:56:54 PM EST$</tag>
<tag name="@since">Baja 1.0</tag>
<extends>
<type class="javax.baja.sys.BajaRuntimeException"/>
</extends>
<implements>
<type class="javax.baja.sys.Localizable"/>
</implements>
<!-- javax.baja.security.AuthenticationException(java.lang.String, java.lang.Throwable, javax.baja.security.AuthenticationRealm) -->
<constructor name="AuthenticationException" public="true">
<parameter name="msg">
<type class="java.lang.String"/>
</parameter>
<parameter name="cause">
<type class="java.lang.Throwable"/>
</parameter>
<parameter name="authenticationRealm">
<type class="javax.baja.security.AuthenticationRealm"/>
</parameter>
<description>
Create with everything.
</description>
</constructor>

<!-- javax.baja.security.AuthenticationException(javax.baja.security.AuthenticationRealm) -->
<constructor name="AuthenticationException" public="true">
<parameter name="authenticationRealm">
<type class="javax.baja.security.AuthenticationRealm"/>
</parameter>
<description>
Create with the specified AuthenticationRealm.
</description>
</constructor>

<!-- javax.baja.security.AuthenticationException(javax.baja.security.AuthenticationRealm, java.lang.Throwable) -->
<constructor name="AuthenticationException" public="true">
<parameter name="authenticationRealm">
<type class="javax.baja.security.AuthenticationRealm"/>
</parameter>
<parameter name="cause">
<type class="java.lang.Throwable"/>
</parameter>
<description>
Create with the specified AuthenticationRealm.
</description>
</constructor>

<!-- javax.baja.security.AuthenticationException(javax.baja.security.AuthenticationRealm, com.tridium.authn.LoginFailureCause) -->
<constructor name="AuthenticationException" public="true">
<parameter name="authenticationRealm">
<type class="javax.baja.security.AuthenticationRealm"/>
</parameter>
<parameter name="loginFailureCause">
<type class="com.tridium.authn.LoginFailureCause"/>
</parameter>
<description>
Create with the specified AuthenticationRealm and LoginFailureCause
</description>
</constructor>

<!-- javax.baja.security.AuthenticationException(java.lang.String) -->
<constructor name="AuthenticationException" public="true">
<parameter name="msg">
<type class="java.lang.String"/>
</parameter>
<description>
Create with specified message.
</description>
</constructor>

<!-- javax.baja.security.AuthenticationException() -->
<constructor name="AuthenticationException" public="true">
<description>
Create with no message.
</description>
</constructor>

<!-- javax.baja.security.AuthenticationException.toString(javax.baja.sys.Context) -->
<method name="toString"  public="true">
<description/>
<parameter name="cx">
<type class="javax.baja.sys.Context"/>
</parameter>
<return>
<type class="java.lang.String"/>
</return>
</method>

<!-- javax.baja.security.AuthenticationException.setLoginFailureCause(com.tridium.authn.LoginFailureCause) -->
<method name="setLoginFailureCause"  public="true">
<description/>
<parameter name="loginFailureCause">
<type class="com.tridium.authn.LoginFailureCause"/>
</parameter>
<return>
<type class="void"/>
</return>
</method>

<!-- javax.baja.security.AuthenticationException.getLoginFailureCause() -->
<method name="getLoginFailureCause"  public="true">
<description/>
<return>
<type class="com.tridium.authn.LoginFailureCause"/>
</return>
</method>

<!-- javax.baja.security.AuthenticationException.getAuthenticationRealm() -->
<method name="getAuthenticationRealm"  public="true">
<description>
If this exception was created with an authentication&#xa; space, then return it.  Otherwise return null.
</description>
<return>
<type class="javax.baja.security.AuthenticationRealm"/>
</return>
</method>

</class>
</bajadoc>
