<?xml version="1.0" encoding="UTF-8"?>
<bajadoc version="2.0" createdBy="niagara-baja-doclet-1.0.9" createdAt="03-May-2024" createdOn="883e7f7a9875">
<class module="baja" runtimeProfile="rt" qualifiedName="javax.baja.security.CancelledAuthenticationException" name="CancelledAuthenticationException" packageName="javax.baja.security" public="true" category="exception">
<description>
This &lt;code&gt;<see ref="javax.baja.security.AuthenticationException">AuthenticationException</see>&lt;/code&gt;&#xa; indicates that authentication failed due to the user cancelling the&#xa; authentication process.
</description>
<tag name="@author">Melanie Coggan</tag>
<tag name="@creation">2014-03-12</tag>
<tag name="@since">Niagara 4.0</tag>
<extends>
<type class="javax.baja.security.AuthenticationException"/>
</extends>
<!-- javax.baja.security.CancelledAuthenticationException() -->
<constructor name="CancelledAuthenticationException" public="true">
<description/>
</constructor>

</class>
</bajadoc>
