<?xml version="1.0" encoding="UTF-8"?>
<bajadoc version="2.0" createdBy="niagara-baja-doclet-1.0.9" createdAt="03-May-2024" createdOn="883e7f7a9875">
<class module="query" runtimeProfile="rt" qualifiedName="javax.baja.query.QueryException" name="QueryException" packageName="javax.baja.query" public="true" category="exception">
<description/>
<tag name="@author">Matthew Giannini</tag>
<tag name="@creation">Apr 15, 2008</tag>
<tag name="@version">$Revision: 1$ $Date: 6/24/08 11:50:04 AM EDT$</tag>
<tag name="@since">Baja 3.4</tag>
<extends>
<type class="java.lang.Exception"/>
</extends>
<!-- javax.baja.query.QueryException(java.lang.Throwable) -->
<constructor name="QueryException" public="true">
<parameter name="cause">
<type class="java.lang.Throwable"/>
</parameter>
<description/>
</constructor>

<!-- javax.baja.query.QueryException(java.lang.String, java.lang.Throwable) -->
<constructor name="QueryException" public="true">
<parameter name="message">
<type class="java.lang.String"/>
</parameter>
<parameter name="cause">
<type class="java.lang.Throwable"/>
</parameter>
<description/>
</constructor>

<!-- javax.baja.query.QueryException(java.lang.String) -->
<constructor name="QueryException" public="true">
<parameter name="message">
<type class="java.lang.String"/>
</parameter>
<description/>
</constructor>

<!-- javax.baja.query.QueryException() -->
<constructor name="QueryException" public="true">
<description/>
</constructor>

</class>
</bajadoc>
