<?xml version="1.0" encoding="UTF-8"?>
<bajadoc version="2.0" createdBy="niagara-baja-doclet-1.0.9" createdAt="03-May-2024" createdOn="883e7f7a9875">
<class module="devHttpDriver" runtimeProfile="rt" qualifiedName="com.tridium.ddfHttp.comm.DdfHttpHelper$IcmpPingFailure" name="DdfHttpHelper.IcmpPingFailure" packageName="com.tridium.ddfHttp.comm" public="true" innerClass="true" category="exception">
<description>
An instance of this exeption is thrown and caught internally&#xa; when trying to establish an HTTP connection if an ICMP ping&#xa; fails to get a response from the other end of the HTTP&#xa; connection.
</description>
<tag name="@author">lperkins</tag>
<extends>
<type class="java.lang.Exception"/>
</extends>
<!-- com.tridium.ddfHttp.comm.DdfHttpHelper.IcmpPingFailure(java.lang.String) -->
<constructor name="IcmpPingFailure" public="true">
<parameter name="localizedMessage">
<type class="java.lang.String"/>
</parameter>
<description/>
</constructor>

</class>
</bajadoc>
