<?xml version="1.0" encoding="UTF-8"?>
<bajadoc version="2.0" createdBy="niagara-baja-doclet-1.0.9" createdAt="03-May-2024" createdOn="883e7f7a9875">
<class module="platform" runtimeProfile="rt" qualifiedName="javax.baja.platform.ICancelHint$CanceledException" name="ICancelHint.CanceledException" packageName="javax.baja.platform" public="true" static="true" innerClass="true" category="exception">
<description>
A long-running method may throw CanceledException to signify&#xa; that its invocation did not complete
</description>
<extends>
<type class="javax.baja.sys.LocalizableRuntimeException"/>
</extends>
<!-- javax.baja.platform.ICancelHint.CanceledException() -->
<constructor name="CanceledException" public="true">
<description/>
</constructor>

</class>
</bajadoc>
